language: csharp
solution: QuizRunner.sln
mono:
  - latest
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore QuizRunner.sln
after_script:
  - nunit-console TestEditor/bin/Release/net46/TestEditor.dll
  - nunit-console TestTesting/bin/Release/net46/TestTesting.dll
